### PR TITLE
Fix bugs handling big inventory

### LINKED ISSUE #1769: Crypto listing inventory not being properly returned
I post  crypto currency listing with the following data:

```
{
  "termsAndConditions": "",
  "refundPolicy": "",
  "item": {
    "title": "BTC-LTC",
    "description": "",
    "tags": [],
    "categories": [],
    "nsfw": false,
    "images": [
      {
        "filename": "hippo.jpg",
        "original": "QmP2qx1LQTmnxeqGewtv2GrfJWRNWmtB7cYa7MQb6pzSxJ",
        "large": "QmaHc6qXMD3ZLkvi6sx3ZUFnWTAoGJvKTFJGCfiRXFSN3Q",
        "medium": "Qmdvf59dhjk4ZiBn2kd7NYGNYAUzPFZXsaLur5Qhgectt5",
        "small": "QmVKi5UPQzqtxfTAmMpyiwH1H62R68KmuXccuyDYz3jFSi",
        "tiny": "QmaeAAqCRWCDK6ieE8YiCnYMLrnTT7TsjkmwEtFEkh7PnS"
      }
    ],
    "options": [],
    "skus": [
      {
        "bigQuantity": "1"
      }
    ],
    "processingTime": "",
    "grams": 0,
    "priceModifier": 2
  },
  "metadata": {
    "contractType": "CRYPTOCURRENCY",
    "format": "MARKET_PRICE",
    "expiry": "2037-12-31T06:00:00.000Z",
    "acceptedCurrencies": [
      "TBTC"
    ],
    "version": 5,
    "language": "",
    "escrowTimeoutHours": 0,
    "coinType": "LTC",
    "coinDivisibility": 8,
    "priceModifier": 2
  },
  "shippingOptions": [],
  "coupons": [],
  "slug": "snooper",
  "vendorID": {
    "peerID": "QmdSm6EBu4qta1a6rEaq3m3ZQABz3L8vrgQ3tDhQdDzLBZ",
    "handle": "",
    "pubkeys": {
      "identity": "CAESIDKozlpCQ/n5xwpSSIoukWyjUjDam3tTXZ58DC2x4xN4",
      "bitcoin": "AyCEDTBZXxCmufnrRm29X0RquiKctpsL6plo6xqClZ3i"
    },
    "bitcoinSig": "MEQCIGBnsWUZXhSkXK9jEFlnbZo8fJENhWmwiTsYZdBBX+HYAiAqmxcn32KSPzlta8dKbJ9KgFbKdqIfBRjtPS9EyabbbQ=="
  },
  "moderators": []
}
```

The key part is the "dummy" SKU, which is how non-variant inventory is represented:

```
    "skus": [
      {
        "bigQuantity": "1"
      }
    ],
```

But on a subsequent GET the inventory is not maintained:

```
            "skus": [
                {
                    "productID": "",
                    "surcharge": 0,
                    "quantity": 0,
                    "bigSurcharge": "",
                    "bigQuantity": "0"
                }
            ],
```

### PR DESCRIPTION
**Pull request by cpacia**
This updates the inventory db interface and implementation to use big ints for inventory and updates all the areas where we do math on inventory. This also gets the crypto currency QA tests passing. 

Should close #1769

### CODE REVIEW

File: core/inventory.go [hunk 1]
```diff
@@ -18,8 +19,8 @@ var (
 
 // InventoryListing is the listing representation stored on IPFS
 type InventoryListing struct {
-	Inventory   int64  `json:"inventory"`
-	LastUpdated string `json:"lastUpdated"`
+	Inventory   *big.Int `json:"inventory"`
```
Comment (placer14) [inline core/inventory.go]: This is not going to marshal to JSON in the way we expect. By default big.Int marshals to int and we probably would rather handle them as strings. https://play.golang.org/p/RvpU9y8wlBD

File: qa/testdata/listing_crypto.json [hunk 2]
```diff
@@ -15,6 +15,12 @@
         "description": "",
         "processingTime": "1 to 2 hours",
         "price": "0",
+        "priceCurrency": {
+            "code": "TETH",
+            "divisibility": 8,
+            "name": "A",
+            "currencyType": "A"
```
Comment (placer14) [inline qa/testdata/listing_crypto.json]: `Name` and `currencyType` aren't persisted in the actual json payloads. We can leave them out of the fixtures.

File: repo/listing.go [hunk 3]
```diff
@@ -1643,14 +1643,24 @@ func (l *Listing) ValidateSkus() error {
...
+		if s.BigQuantity != "" {
+			amtStr = s.BigQuantity
+		} else {
+			amtStr = strconv.Itoa(int(s.Quantity))
+		}
+		amt, ok := new(big.Int).SetString(amtStr, 10)
+		if !ok {
+			return nil, errors.New("error parsing inventory")
+		}
+		inventory[i] = amt
```
Comment (placer14) [inline repo/listing.go]: Would it be better to select by ListingVersion?
