### PR TITLE
(#1949) Fix patching profile with moderator fee

### LINKED ISSUE #1946: Server does not clear out unneeded moderatorInfo fields based on the fee type
Here's my profile:

https://pastebin.com/b5jvEQJW

I send a PATCH with the following payload:

```
{
  "moderator": true,
  "moderatorInfo": {
    "fee": {
      "feeType": "PERCENTAGE",
      "percentage": 10
    },
    "description": "Describe the scribe.",
    "termsAndConditions": "The terms are germs.",
    "languages": [
      "en-US"
    ]
  }
}
```

It errors with:

invalid profile: percentage moderator fee should not include a fixed fee or should use (FIXED_PLUS_PERCENTAGE) feeType

Expectation:
The server will infer which fields moderatorInfo fields in the profile are needed based off of the provided feeType and clear out / reset unneeded ones.

### PR DESCRIPTION
**Pull request by cpacia**
closes #1946

### CODE REVIEW

File: core/profile.go [hunk 1]
```diff
@@ -195,6 +195,12 @@ func (n *OpenBazaarNode) PatchProfile(patch map[string]interface{}) error {
 
 	repoProfile.NormalizeDataForAllSchemas()
 
+	if repoProfile.GetProtobuf().ModeratorInfo != nil && repoProfile.GetProtobuf().ModeratorInfo.Fee != nil {
+		if repoProfile.GetProtobuf().ModeratorInfo.Fee.FeeType == pb.Moderator_Fee_PERCENTAGE {
```
Comment (hoffmabc) [inline core/profile.go]: Why not just make a single if condition rather than a nested conditional?

Comment (cpacia) [reply core/profile.go]: Yeah I guess that could work too. I was just thinking about the nil checks as being separate.
