### PR TITLE
(#1801) Fix surcharge parsing error on purchase

### LINKED ISSUE #1801: Purchase of a listing without variants is failing with a missing surcharge
The following purchase payload:

```
{
  "address": "",
  "addressNotes": "",
  "alternateContactInfo": "",
  "city": "",
  "countryCode": "",
  "items": [
    {
      "listingHash": "QmcQeWiCPrAcFJemXhd2oyqVoytRf8SNyYopUAiAYiTZnR",
      "options": [],
      "shipping": {
        "name": ""
      },
      "memo": "",
      "coupons": [],
      "bigQuantity": "1"
    }
  ],
  "moderator": "",
  "paymentCoin": "LTC",
  "postalCode": "",
  "shipTo": "",
  "state": ""
}
```

fails with an `invalid surcharge value` error.

The listing being purchased does not have any variants. What surcharge is it expecting?

Here is the listing data:

```
{
    "listing": {
        "slug": "test-test-test-chowdah",
        "vendorID": {
            "peerID": "Qma14uKNrz9rVZoKmXDq8439wPZg9o8wz968EucUfU1Lh4",
            "handle": "",
            "pubkeys": {
                "identity": "CAESIPRXZFIbHlWvcSDo592lVr/HT4z0WILdrW8NjWK6PJYQ",
                "bitcoin": "AxZsdkL0aBpo9CACnZYYSnzE5x6duy6RjwlIpyEy88Uh"
            },
            "bitcoinSig": "MEUCIQDtJluiQJA+cjmHgjlzgm1QKwmjVGFBWKoeE2e81uh0PQIgTZWEm+qmiJ5+f8NGeKOp5t+/waumdXrpdWqOei4JONk="
        },
        "metadata": {
            "version": 5,
            "contractType": "DIGITAL_GOOD",
            "format": "FIXED_PRICE",
            "expiry": "2037-12-31T06:00:00.000Z",
            "acceptedCurrencies": [
                "BTC",
                "BCH",
                "ZEC",
                "LTC",
                "ETH"
            ],
            "pricingCurrency": "",
            "language": "",
            "escrowTimeoutHours": 1080,
            "coinType": "",
            "coinDivisibility": 0,
            "priceModifier": 0
        },
        "item": {
            "title": "TEST TEST TEST chowdah",
            "description": "",
            "processingTime": "",
            "price": 0,
            "nsfw": false,
            "tags": [
            ],
            "images": [
                {
                    "filename": "alvinshow01.gif",
                    "original": "Qmc6qbG2jV5dtfSJhzHCxgJJGjABCHQmXGJcDKuGmswV4p",
                    "large": "QmYKDiFCMYR9pirv99zGm6kHZ2s5LRq55j31BLbbuSKxqA",
                    "medium": "QmUYd1VrE9tcGe67ZW8o3E2DEiJ8PurTE45yiVucfhaSmG",
                    "small": "QmcPuwmTMRz6im32HXYTcaXPpzPb4pzVTDBycr8USBXQ6y",
                    "tiny": "QmaJKHgeidwWQ2kzy4VwE8cvGwo64QYLSA5mEosiu9ZmoT"
                }
            ],
            "categories": [
            ],
            "grams": 0,
            "condition": "NEW",
            "options": [
            ],
            "skus": [
                {
                    "productID": "",
                    "surcharge": 0,
                    "quantity": 0,
                    "bigSurcharge": "",
                    "bigQuantity": "0"
                }
            ],
            "priceModifier": 0,
            "bigPrice": "10000",
            "priceCurrency": {
                "code": "LTC",
                "divisibility": 8
            }
        },
        "shippingOptions": [
        ],
        "coupons": [
        ],
        "moderators": [
        ],
        "termsAndConditions": "",
        "refundPolicy": ""
    },
    "hash": "QmcQeWiCPrAcFJemXhd2oyqVoytRf8SNyYopUAiAYiTZnR",
    "signature": "2J8h/vTT+48V/ftUs4OnaWa9Ak+zAApvIDaKHFzx9p1H9+5Tf26Yt+kkLk4laGX2RFsZKMPtDPh1AAWrH/kiBQ=="
}
```

### PR DESCRIPTION
**Pull request by cpacia**
closes #1801

### CODE REVIEW

File: repo/listing.go [hunk 1]
```diff
@@ -1057,16 +1057,27 @@ func (l *Listing) GetOptions() ([]*pb.Listing_Item_Option, error) {
 // GetSkus - return item skus
 func (l *Listing) GetSkus() ([]*pb.Listing_Item_Sku, error) {
 	var (
-		sl  = &pb.SignedListing{}
-		err = json.Unmarshal(l.ListingBytes, &sl)
+		pbl = &pb.Listing{}
+		err = jsonpb.UnmarshalString(string(l.ListingBytes), pbl)
```
Comment (placer14) [inline repo/listing.go]: Does this occur in other places?

Comment (cpacia) [reply repo/listing.go]: It looks like the other places it's appropriate to use regular JSON.
