### PR TITLE
(#1499) Fix double amount in payment record

### LINKED ISSUE #1499: Double the payment amount coming out of the 1 of 2 multi-sig for a crypto currency order
Here's the order data returned by `ob/order/<order-id>`:

```
{
    "contract": {
        "vendorListings": [
            {
                "slug": "btc-xmr",
                "vendorID": {
                    "peerID": "QmNU2H1S1gNf782s9gvFFV9jUKBSy7uuWU8QtAA2N3bhFZ",
                    "handle": "",
                    "pubkeys": {
                        "identity": "CAESIKprq8wuWnTgNxi+8GhcgPR/ZMMlliWOX1NUTXAkmEw7",
                        "bitcoin": "AlvixFdyZPFh9UhCDXt0lwDQZ3TiqUWphJWXDx7T/UAZ"
                    },
                    "bitcoinSig": "MEUCIQC5GwJpvtYWlHmFGQTlrmnA90M1uiGi+PY8u0dNn9eKBQIgU7sISX9fccMREZtZz9AEm+3FKQSPjUh9O+veMbBiQiY="
                },
                "metadata": {
                    "version": 4,
                    "contractType": "CRYPTOCURRENCY",
                    "format": "MARKET_PRICE",
                    "expiry": "2037-12-31T05:00:00.000Z",
                    "acceptedCurrencies": [
                        "BTC"
                    ],
                    "pricingCurrency": "",
                    "language": "",
                    "escrowTimeoutHours": 1080,
                    "coinType": "XMR",
                    "coinDivisibility": 100000000,
                    "priceModifier": 0
                },
                "item": {
                    "title": "BTC-XMR",
                    "description": "Get your best Monero here.",
                    "processingTime": "",
                    "price": 0,
                    "nsfw": false,
                    "tags": [
                        "monero",
                        "xmr"
                    ],
                    "images": [
                        {
                            "filename": "U5du1FSQXAh8BPUBL84QqKKpD6PJAYA_1680x8400.jpeg",
                            "original": "zb2rheBY5QtqqzwFEAGambX4AipxgtpSH6EFm1i6CLpxSVdUE",
                            "large": "zb2rhnk6bz6HjutpxFS54WfYr8JKV1eexoVQHGUpy5hzsdqDN",
                            "medium": "zb2rhX152aiNkv7iCcYKSkYXVPkSQfKwZ9Z3QFj5TYn1r6zzG",
                            "small": "zb2rhZTYAfQLXToZQsqH43gJ8kVoiA8tYvzA9tMbBAcvTkHps",
                            "tiny": "zb2rha25PhWHqB6WrCh3J24q7NV39iZjfWuZwUNBTbkkMy21K"
                        },
                        {
                            "filename": "download (1).jpeg",
                            "original": "zb2rhgsdYpiZY44PxPVhRmQZNMtnm9uzyxNapMnV3YA4bHSJv",
                            "large": "zb2rhj6914zfZBFRkk1cKkMaaHJASfAPQgW69MhEvyUJg25gf",
                            "medium": "zb2rhaG8TxKVw9LvE5LinP5eAW4UBF9QVq52uhxYXYcuBZtTW",
                            "small": "zb2rhgH77VP8v1pqSSKshB47m7jNyD436Z55vZktX4xFa7ydJ",
                            "tiny": "zb2rhZ5Fx3TksY9vhCoxJBydbSwZ1BCsRz3fL8RYJzTf64Yn1"
                        }
                    ],
                    "categories": [
                        "Coins"
                    ],
                    "grams": 0,
                    "condition": "",
                    "options": [
                    ],
                    "skus": [
                        {
                            "productID": "",
                            "surcharge": 0,
                            "quantity": 0
                        }
                    ]
                },
                "shippingOptions": [
                ],
                "coupons": [
                ],
                "moderators": [
                    "QmVFNEj1rv2d3ZqSwhQZW2KT4zsext4cAMsTZRt5dAQqFJ",
                    "QmduBPTQNaXYWivhjNEs8fx5psgazDpH4x1DJqtTcVXhPs",
                    "QmUbvQJPSm2i5daancGbBuLtucwc1dftberuVcdCxpSEDr",
                    "QmcscQDiCuTSGxBeMD9qyXwRMcbLU5m9P1kupojYJdFdoh"
                ],
                "termsAndConditions": "",
                "refundPolicy": ""
            }
        ],
        "buyerOrder": {
            "refundAddress": "1LgnoZZorj6ThC8AYKnQ45YUsH77a8KKC",
            "refundFee": 5,
            "shipping": {
                "shipTo": "",
                "address": "",
                "city": "",
                "state": "",
                "postalCode": "",
                "country": "NA",
                "addressNotes": ""
            },
            "buyerID": {
                "peerID": //hidden
                "handle": "",
                "pubkeys": {
                    "identity": "CAESINs2tAJjdkhrkaxpZyLH5GmoGKxZWwIoIzan45ENgoFs",
                    "bitcoin": "AsS9nxsrjERGtoISKhv8ZunAbTZ9x+hoygqMlJqqYaoW"
                },
                "bitcoinSig": "MEUCIQCo3jCNTIeu3TCx4SE3yRykt5mASrTOqN3tHgSv81rlnwIgegiK4BhsKPi34vw2Huc17KwboDkE2FdJhydXxl8YI5o="
            },
            "timestamp": "2018-10-22T19:27:09.102163200Z",
            "items": [
                {
                    "listingHash": "zb2rhZNDjeQ6FUP2K66TyAQivY54AVBrbeV7YXqGHxhjd4Rhe",
                    "quantity": 0,
                    "quantity64": 25000000,
                    "memo": "",
                    "paymentAddress": "45km6Sj2uV9NRdFTfmbhWXVE9zqy1LJLjR4NdyowUv58XU4dS1VdLz53gX8CMuCEpjFvBAw8mdrw3ASfnn4sHfwhEScqwht"
                }
            ],
            "payment": {
                "method": "MODERATED",
                "moderator": "QmduBPTQNaXYWivhjNEs8fx5psgazDpH4x1DJqtTcVXhPs",
                "amount": 403994,
                "chaincode": "0b0722e5fd5fd41813ad947d657e2ec5ae09626eb98e6426834b0859e12cc933",
                "address": "bc1qx974cytsrqnyxsu9ver70whtmuk9u7q8sg7yw47k3j7f93avwd9snxk592",
                "redeemScript": "63522102bbc0782127a5e0fb84f26c362c0c540763a75b339ef60449c4f0e1c1fc97f07521020db3e551304973574ed56c60a991f2e8a55e45db82da0451b50ee5353e528af52102cd457ea03e4a26d29c8886ea55b119421990d08217d7549b51f3efbeae3fd0f353ae67025019b27521020db3e551304973574ed56c60a991f2e8a55e45db82da0451b50ee5353e528af5ac68",
                "moderatorKey": "As1FfqA+SibSnIiG6lWxGUIZkNCCF9dUm1Hz776uP9Dz",
                "coin": "BTC"
            },
            "ratingKeys": [
                "Ahuu6yG5KzBufmpdWVO3Pv0+hBH/MU5r/85BSx7KfQfW"
            ],
            "alternateContactInfo": "",
            "version": 2
        },
        "vendorOrderConfirmation": {
            "orderID": "QmSY2d7U9GjFxuzdazuxRsmf3fhWjxpjonCatFFu5XdREG",
            "timestamp": "2018-10-23T14:57:47.841387Z",
            "paymentAddress": "bc1qx974cytsrqnyxsu9ver70whtmuk9u7q8sg7yw47k3j7f93avwd9snxk592",
            "requestedAmount": 403994,
            "ratingSignatures": [
                {
                    "metadata": {
                        "listingSlug": "btc-xmr",
                        "moderatorKey": "As1FfqA+SibSnIiG6lWxGUIZkNCCF9dUm1Hz776uP9Dz",
                        "listingTitle": "BTC-XMR",
                        "thumbnail": {
                            "tiny": "zb2rha25PhWHqB6WrCh3J24q7NV39iZjfWuZwUNBTbkkMy21K",
                            "small": "zb2rhZTYAfQLXToZQsqH43gJ8kVoiA8tYvzA9tMbBAcvTkHps",
                            "medium": "zb2rhX152aiNkv7iCcYKSkYXVPkSQfKwZ9Z3QFj5TYn1r6zzG",
                            "large": "zb2rhnk6bz6HjutpxFS54WfYr8JKV1eexoVQHGUpy5hzsdqDN",
                            "original": "zb2rheBY5QtqqzwFEAGambX4AipxgtpSH6EFm1i6CLpxSVdUE"
                        }
                    },
                    "signature": "jIwdAp7SwS0vZflE6udB349g3eye0qRZ08+Y/iAVqrW+yVbUxkMe7ShBzndQZG8nYc6iVSDJ4bQR8OEw+vJTBw=="
                }
            ]
        },
        "refund": {
            "orderID": "QmSY2d7U9GjFxuzdazuxRsmf3fhWjxpjonCatFFu5XdREG",
            "timestamp": "2019-03-13T14:31:05.247267Z",
            "sigs": [
                {
                    "inputIndex": 0,
                    "signature": "MEUCIQCXauahVdry5+FGt//YfeEfKnYY8Wv19oRKlbFB2L4Q8wIgOzwNuMawGjQPRhsRAXS2oATaOd7GCqCHzVjWf47DKo0B"
                }
            ],
            "memo": ""
        },
        "signatures": [
            {
                "section": "LISTING",
                "signatureBytes": "8N6vYS3bnlR3XezQt4V1zZaiUF9bRB7x3lY+m7vo6Casd3FLDZJi1tzAIuqvOQiABoB62jEiC4I2ZUsCeThECQ=="
            },
            {
                "section": "ORDER",
                "signatureBytes": "M1RzEFFAsAJNu0p/fnJztNhcJP6zy4YzSTde+r1VaIF/u8vUa1+qWYpKczGa/kalCdUdjpekVTfbE16DBHDMAQ=="
            },
            {
                "section": "ORDER_CONFIRMATION",
                "signatureBytes": "8gw4eTnsYdxVWMlBP6FWGiLk7iJpBClBI6GGwelxzqwZY/PB6etG/lCNtXAnkM7dcNKawaPVBzH271EmPWxcDw=="
            }
        ]
    },
    "state": "REFUNDED",
    "read": true,
    "funded": true,
    "unreadChatMessages": 0,
    "paymentAddressTransactions": [
        {
            "txid": "1272b128420a8b210f88bfb63058f5045fb8105e9cc7137e8593de188e2066e3",
            "value": 403994,
            "confirmations": 20185,
            "height": 546901,
            "timestamp": "2018-10-22T19:27:24.804061300Z"
        },
        {
            "txid": "f0813ea0cc4b245a77abafb19b78d9f41cd559983bf9ac0066b76aaf586f5b58",
            "value": -807988,
            "confirmations": 142,
            "height": 566944,
            "timestamp": "2019-03-13T14:39:43.752164Z"
        }
    ],
    "refundAddressTransaction": {
        "txid": "f0813ea0cc4b245a77abafb19b78d9f41cd559983bf9ac0066b76aaf586f5b58",
        "value": 807988,
        "confirmations": 142,
        "height": 566944,
        "timestamp": "2019-03-13T14:39:43.752164Z"
    }
}
```

Notice also that a refund returns the double payment amount. Curious to know where half of that double amount is coming from?

Originally logged in the desktop repo:
https://github.com/OpenBazaar/openbazaar-desktop/issues/1719

### PR DESCRIPTION
**Pull request by cpacia**
This code was trying to avoid an edge case where multiple outputs in the
same transaction paid the payment address but this should already have
been accounted for when the record was saved in the db and the values
already aggregated. Thus this was causing incorrect amounts to be saved.
closes #1499

### CODE REVIEW

File: core/utils.go [hunk 1]
```diff
@@ -2,6 +2,7 @@ package core
 
 import (
 	"fmt"
+	"github.com/golang/protobuf/ptypes"
```
Comment (placer14) [inline core/utils.go]: Please move this back.

**Comment by cpacia** [comment]
I spent some time trying to figure out how best to test it and couldn't really come up with anything since it makes a call to the wallet and we don't yet have any kind of mock wallet capability. So the tests I was trying to write would fail when asking the wallet for how many confirmations the transaction had.
