### PR TITLE
Fix bug running setapicreds command

### LINKED ISSUE #1471: setapicreds fails with "key has no attributes"
```
$ go run openbazaard.go setapicreds -d /var/lib/openbazaar/
Enter username: asdf
Enter a veerrrry strong password:
Confirm your password:
 key has no attributes
exit status 1
```

Fails on this line in `cmd/setapicreds.go`
```
 err = r.SetConfigKey("JSON-API", apiCfg)
```

Contents of `apiCfg` looks like this:
```
(dlv) p apiCfg
*github.com/OpenBazaar/openbazaar-go/schema.APIConfig {
        Authenticated: true,
        AllowedIPs: []string len: 0, cap: 0, [],
        Username: "",
        Password: "15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225",
        CORS: *string nil,
        Enabled: true,
        HTTPHeaders: map[string]interface {} nil,
        SSL: false,
        SSLCert: "",
        SSLKey: "",}
```

### PR DESCRIPTION
**Pull request by cpacia**
closes #1471

### CODE REVIEW

File: cmd/setapicreds.go [hunk 1]
```diff
@@ -32,21 +34,25 @@ func (x *SetAPICreds) Execute(args []string) error {
 	if x.DataDir != "" {
 		repoPath = x.DataDir
 	}
-	r, err := fsrepo.Open(repoPath)
+	cfgPath := path.Join(repoPath, "config")
+	configFile, err := ioutil.ReadFile(cfgPath)
```
Comment (tyler-smith) [inline cmd/setapicreds.go]: This `err` value is not checked
